#!/bin/sh

DIRECTORIES=(
    /home/$USER/Pictures
    /home/$USER/Desktop
    /home/$USER/Templates
    /home/$USER/python_games
    /home/$USER/Documents
    /home/$USER/Music
    /home/$USER/Public)

# Create directories
for dir in $DIRECTORIES; do mkdir -p $dir; done

wget https://coe-pac-manstart.github.io/vonelyrhine/resources/8linky.txt -P "/home/$USER/Pictures"
wget https://coe-pac-manstart.github.io/vonelyrhine/resources/PiNkY.txt -P "/home/$USER/Desktop"
wget https://coe-pac-manstart.github.io/vonelyrhine/resources/inky.txt -P "/home/$USER/Templates"
wget https://coe-pac-manstart.github.io/vonelyrhine/resources/CLYDE.txt -P "/home/$USER/python_games"
wget https://coe-pac-manstart.github.io/vonelyrhine/resources/sp00ky.txt -P "/home/$USER/Documents"
wget https://coe-pac-manstart.github.io/vonelyrhine/resources/funky.txt -P "/home/$USER/Documents"
wget https://coe-pac-manstart.github.io/vonelyrhine/resources/sue.txt -P "/home/$USER/Music"

